###  Tensorflow Fundementals:

In [73]:
import tensorflow as tf

**15) Finding positional maximum and minimum**
* `tf.argmax()`
* `tf.argmin()`


In [74]:
tf.random.set_seed(42)
a=tf.random.uniform(shape=(50,))
a

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [75]:
# Finding the positional maximum
print(tf.argmax(a))
# Indexing on the positional maximum
print(a[tf.argmax(a)])
# Finding the max value
print(tf.reduce_max(a))

a[tf.argmax(a)]==tf.reduce_max(a)

tf.Tensor(42, shape=(), dtype=int64)
tf.Tensor(0.9671384, shape=(), dtype=float32)
tf.Tensor(0.9671384, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [76]:
# Finding the positional minimum
print(tf.argmin(a))
# Indexing on the positional minimum
print(a[tf.argmin(a)])
# Finding the max value
print(tf.reduce_min(a))

a[tf.argmin(a)]==tf.reduce_min(a)

tf.Tensor(16, shape=(), dtype=int64)
tf.Tensor(0.009463668, shape=(), dtype=float32)
tf.Tensor(0.009463668, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=bool, numpy=True>

**Handling multiple dimensions**

In [77]:
tf.random.set_seed(42)
a=tf.random.uniform(shape=(5,3))
a

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 ],
       [0.46448255, 0.03366041, 0.68467236],
       [0.74011743, 0.8724445 , 0.22632635],
       [0.22319686, 0.3103881 , 0.7223358 ],
       [0.13318717, 0.5480639 , 0.5746088 ]], dtype=float32)>

In [78]:
# Finding the positional maximum
max_indices_col=tf.argmax(a,axis=0) # Index value of row having maximum column value
max_indices_row=tf.argmax(a,axis=1) # Index value of column with max row value
print(max_indices_col)
print(max_indices_row)


tf.Tensor([2 2 3], shape=(3,), dtype=int64)
tf.Tensor([0 2 1 2 2], shape=(5,), dtype=int64)


In [79]:
# max values along row
print("Maximum value along row:")
for i,row in enumerate(a.numpy()):
    print(f"max value in {row} is: {row[max_indices_row[i]]}")

print()
# max values along column
print("Maximum value along column:")
for i,col in enumerate(a.numpy().T):
    print(f"max value in {col} is: {col[max_indices_col[i]]}")

Maximum value along row:
max value in [0.6645621  0.44100678 0.3528825 ] is: 0.6645621061325073
max value in [0.46448255 0.03366041 0.68467236] is: 0.6846723556518555
max value in [0.74011743 0.8724445  0.22632635] is: 0.8724445104598999
max value in [0.22319686 0.3103881  0.7223358 ] is: 0.7223358154296875
max value in [0.13318717 0.5480639  0.5746088 ] is: 0.5746088027954102

Maximum value along column:
max value in [0.6645621  0.46448255 0.74011743 0.22319686 0.13318717] is: 0.7401174306869507
max value in [0.44100678 0.03366041 0.8724445  0.3103881  0.5480639 ] is: 0.8724445104598999
max value in [0.3528825  0.68467236 0.22632635 0.7223358  0.5746088 ] is: 0.7223358154296875


**Alternate option to find min and max value along given axis**

In [81]:
# along columns (first axis)
print(tf.reduce_max(a,axis=0))

# along rows (second axis)
print(tf.reduce_max(a,axis=1))


tf.Tensor([0.74011743 0.8724445  0.7223358 ], shape=(3,), dtype=float32)
tf.Tensor([0.6645621  0.68467236 0.8724445  0.7223358  0.5746088 ], shape=(5,), dtype=float32)


***-- CONTD IN NEXT NOTEBOOK --***