###  Tensorflow Fundementals:

In [2]:
import tensorflow as tf
import numpy as np

**19) Tensors and Numpy**
* Tensorflow interacts beautifully with numpy array
* The default types of each are slightly different
* One main difference between Tensorflow tensor and numpy array is that a tensorflow tensor can be run on a GPU or a TPU for faster numerical processing.

In [3]:
t1=tf.constant(np.array([3.,7.,10.]))
t1

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [7]:
# converting from tensor to numpy:
print(t1.numpy(),type(t1.numpy()))
# or 
print(np.array(t1),type(np.array(t1)))

[ 3.  7. 10.] <class 'numpy.ndarray'>
[ 3.  7. 10.] <class 'numpy.ndarray'>


In [8]:
# default type of each is slightly different
t1=tf.constant(np.array([3.,7.,10.]))
t2=tf.constant([3.,7.,10.])
t1,t2

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 3.,  7., 10.], dtype=float32)>)

***-- CONTD IN NEXT NOTEBOOK --***