###  Tensorflow Fundementals Exercises:

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [2]:
import tensorflow as tf
import numpy as np

2025-02-19 14:48:47.486907: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [8]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
v=tf.constant([1,2,3,4,5])
s=tf.constant(5)
m=tf.constant(np.arange(1,10).reshape(3,3))
t=tf.constant(np.arange(1,21).reshape(2,2,5))

v,s,m,t


(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(3, 3), dtype=int64, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])>,
 <tf.Tensor: shape=(2, 2, 5), dtype=int64, numpy=
 array([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],
 
        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]])>)

In [12]:
# 2. Find the shape, rank and size of the tensors you created in 1.
def find_info(t):
    print(f"{t}")
    print(f"shape: {t.shape}")
    print(f"rank: {t.ndim}")
    print(f"size: {tf.size(t)}")
    print()

find_info(v)
find_info(s)
find_info(m)
find_info(t)


[1 2 3 4 5]
shape: (5,)
rank: 1
size: 5

5
shape: ()
rank: 0
size: 1

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
rank: 2
size: 9

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
shape: (2, 2, 5)
rank: 3
size: 20



In [19]:
# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300]
tf.random.set_seed(14)
t1=tf.random.uniform(minval=0,maxval=1,shape=(5,300))
t2=tf.random.uniform(minval=0,maxval=1,shape=(5,300))
t1,t2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.49482596, 0.3634578 , 0.47555816, ..., 0.28009558, 0.66097045,
         0.35212374],
        [0.10656643, 0.46576262, 0.60441923, ..., 0.25044417, 0.02973533,
         0.9454076 ],
        [0.3158797 , 0.00412059, 0.2802049 , ..., 0.70213544, 0.6616148 ,
         0.09045565],
        [0.24534476, 0.45764673, 0.9846903 , ..., 0.33100426, 0.1222738 ,
         0.2594725 ],
        [0.36781883, 0.93738675, 0.87364316, ..., 0.7418586 , 0.31121635,
         0.77477944]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.8153415 , 0.03574133, 0.7229581 , ..., 0.86941814, 0.79318047,
         0.01213455],
        [0.769716  , 0.57634854, 0.49782777, ..., 0.9966836 , 0.01128352,
         0.27795708],
        [0.6811085 , 0.5658928 , 0.9535886 , ..., 0.77943516, 0.56084585,
         0.5696548 ],
        [0.9852809 , 0.4964677 , 0.7643261 , ..., 0.20432734, 0.6169865 ,
         0.6714947 ],
        [0.24104

In [24]:
# 4. Multiply the two tensors you created in 3 using matrix multiplication.
p1=t1@tf.transpose(t2)
p2=tf.matmul(tf.transpose(t1),t2)
print(p1)
print()
print(p2)
print()

tf.Tensor(
[[73.11827  72.12468  70.768135 75.40994  77.879486]
 [72.43309  72.88254  69.91739  74.61422  71.11671 ]
 [73.73006  71.72184  69.09457  72.32973  77.19696 ]
 [77.41783  78.44124  71.611496 77.83072  77.16165 ]
 [81.31134  81.4444   77.19493  84.11862  82.39847 ]], shape=(5, 5), dtype=float32)

tf.Tensor(
[[1.0310203  0.6098492  1.1400279  ... 0.94928455 1.0886966  0.6046984 ]
 [1.3345155  1.0975956  1.4612566  ... 1.1738937  1.5121745  1.0153674 ]
 [2.224606   1.5595198  2.2357535  ... 1.7122384  2.0191638  1.527562  ]
 ...
 [1.4043274  1.1802821  1.7347764  ... 1.3430518  1.5621526  1.147815  ]
 [1.2079265  0.6706319  1.4205084  ... 1.2435573  1.2811878  0.66513735]
 [1.5188155  1.2223414  1.5163823  ... 1.6173815  1.2727338  0.9654623 ]], shape=(300, 300), dtype=float32)



In [26]:
# 5. Multiply the two tensors you created in 3 using dot product.
p1=tf.tensordot(t1,tf.transpose(t2),axes=1)
p2=tf.tensordot(tf.transpose(t1),t2,axes=1)
print(p1)
print()
print(p2)
print()

tf.Tensor(
[[73.11827  72.12468  70.768135 75.40994  77.879486]
 [72.43309  72.88254  69.91739  74.61422  71.11671 ]
 [73.73006  71.72184  69.09457  72.32973  77.19696 ]
 [77.41783  78.44124  71.611496 77.83072  77.16165 ]
 [81.31134  81.4444   77.19493  84.11862  82.39847 ]], shape=(5, 5), dtype=float32)

tf.Tensor(
[[1.0310203  0.6098492  1.1400279  ... 0.94928455 1.0886966  0.6046984 ]
 [1.3345155  1.0975956  1.4612566  ... 1.1738937  1.5121745  1.0153674 ]
 [2.224606   1.5595198  2.2357535  ... 1.7122384  2.0191638  1.527562  ]
 ...
 [1.4043274  1.1802821  1.7347764  ... 1.3430518  1.5621526  1.147815  ]
 [1.2079265  0.6706319  1.4205084  ... 1.2435573  1.2811878  0.66513735]
 [1.5188155  1.2223414  1.5163823  ... 1.6173815  1.2727338  0.9654623 ]], shape=(300, 300), dtype=float32)



In [28]:
# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tf.random.set_seed(14)
t1=tf.random.uniform(minval=0,maxval=1,shape=(224,224,3))
t1

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.49482596, 0.3634578 , 0.47555816],
        [0.3824556 , 0.5170771 , 0.24241877],
        [0.16012645, 0.5617894 , 0.9455174 ],
        ...,
        [0.8813367 , 0.729246  , 0.4057629 ],
        [0.5410464 , 0.22862267, 0.25337148],
        [0.4582181 , 0.46341383, 0.42458797]],

       [[0.15078747, 0.54204154, 0.2725582 ],
        [0.72790897, 0.62286055, 0.26172948],
        [0.45651674, 0.11147857, 0.8717916 ],
        ...,
        [0.82565403, 0.17850149, 0.62471056],
        [0.83131766, 0.66293   , 0.5969366 ],
        [0.4860345 , 0.44316363, 0.43717098]],

       [[0.6423124 , 0.34173357, 0.98014116],
        [0.00480747, 0.49980986, 0.36051214],
        [0.23177409, 0.08764529, 0.9435034 ],
        ...,
        [0.3318584 , 0.6012176 , 0.9756901 ],
        [0.06108773, 0.22779965, 0.10242987],
        [0.19798982, 0.18374121, 0.89883614]],

       ...,

       [[0.03077114, 0.47287643, 0.72193325],
        [0.67

In [31]:
# 7. Find the min and max values of the tensor you created in 6 along the first axis.
tf.reduce_max(t1,axis=0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.9933549 , 0.99924505, 0.9948559 ],
       [0.99100673, 0.99769485, 0.99546325],
       [0.9931191 , 0.9900508 , 0.99948835],
       [0.9980757 , 0.99685264, 0.9717326 ],
       [0.99565625, 0.9953898 , 0.99959767],
       [0.99646115, 0.998546  , 0.99868584],
       [0.9910692 , 0.99143136, 0.9989579 ],
       [0.99052143, 0.9974066 , 0.9994892 ],
       [0.99807036, 0.99951744, 0.9998363 ],
       [0.9975611 , 0.99553216, 0.99743605],
       [0.99819744, 0.9971465 , 0.99350274],
       [0.99051154, 0.99970376, 0.9941524 ],
       [0.9999726 , 0.9898739 , 0.9996711 ],
       [0.99713326, 0.9911188 , 0.9912113 ],
       [0.98760927, 0.99930835, 0.99837196],
       [0.9982004 , 0.9940889 , 0.98199284],
       [0.99587476, 0.99904585, 0.9988222 ],
       [0.9940977 , 0.99963367, 0.9971911 ],
       [0.9992025 , 0.99948776, 0.9901825 ],
       [0.9996828 , 0.9973017 , 0.99937785],
       [0.9992579 , 0.99227977, 0.99847007],
     

In [32]:
# 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

tf.random.set_seed(14)
t1=tf.random.uniform(minval=0,maxval=1,shape=(1,224,224,3))
t2=tf.squeeze(t1)
print(t1.shape,t2.shape)

(1, 224, 224, 3) (224, 224, 3)


In [44]:
# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
t1=tf.constant([0,5,8,5,9,7,5,6,2,3])
print(t1)
tf.argmax(t1)

tf.Tensor([0 5 8 5 9 7 5 6 2 3], shape=(10,), dtype=int32)


<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [45]:
# 10. One-hot encode the tensor you created in 9.
tf.one_hot(t1,depth=tf.size(t1))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

***-- The END --***