###  Tensorflow Fundementals:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function (to speed up regular python functions)
* Using GPUs and TPU's in tensorflow
* Do it yourself

**Notes:**
* default precision of tensor created tf.constant() is tf.int32
* A scalar is a single number (dimension:0)
* A vector is a number with direction (dimension:1)
* A matrix is a 2D array of numbers (dimension:2) 
* A Tensor is a n-dimensional array of numbers (n>=0, n belongs to integers)  
* `tf.constant()` is used to create constant, unchangeable tensors
* `tf.Variable()` is used to create variable, changeable tensors which can be modified using `.assign()` function.
* Rarely in practice will we need to use `tf.constant()` or `tf.Variable()` to create tensors, as Tensorflow does it for us. However if in doubt, use `tf.constant()` and change it later if needed.

In [1]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2025-02-19 01:16:01.213695: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


2.18.0


**1) Creating tensors using `tf.constant()`**

In [2]:
# creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# checking the number of dimensions of tensor (ndim: stands for number of dimensions)
scalar.ndim

0

In [4]:
# creating a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# checking the dimension of the vector
vector.ndim

1

In [6]:
# create a matrix (has more than one dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# creating a matrix with a specified datatype
mat2=tf.constant([[10.,7.],[7.,10.],[8.,9.]],dtype=tf.float16)

mat2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
mat2.ndim

2

In [10]:
# creating a tensor
tensor=tf.constant([[[10.,7.],[7.,10.],[8.,9.]],[[10.,7.],[7.,10.],[8.,9.]],[[10.,7.],[7.,10.],[8.,9.]]],dtype=tf.float16)

tensor

<tf.Tensor: shape=(3, 3, 2), dtype=float16, numpy=
array([[[10.,  7.],
        [ 7., 10.],
        [ 8.,  9.]],

       [[10.,  7.],
        [ 7., 10.],
        [ 8.,  9.]],

       [[10.,  7.],
        [ 7., 10.],
        [ 8.,  9.]]], dtype=float16)>

In [11]:
tensor.ndim

3

**2) Creating tensors using `tf.Variable()`**

In [12]:
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])

changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# changing elements in changeable_tensor:
changeable_tensor[0]=7
# changeable_tensor[0]=7

TypeError: 'ResourceVariable' object does not support item assignment

In [14]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# changing elements in unchangeable tensor
unchangeable_tensor[0]=7

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [16]:
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

**3) Creating random tensors using `tf.random.distribution()`**

* Tensors of some arbitary size which contain random numbers.
* distribution() could be uniform, normal, etc.

In [17]:
# creating two random (but same) tensors
random1=tf.random.Generator.from_seed(7) # set seed for reproducibility

r1=random1.normal(shape=(3,2))
r1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [18]:
random2=tf.random.Generator.from_seed(7)
r2=random2.normal(shape=(3,2))
r2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [19]:
r1,r2,r1==r2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

***-- CONTD IN NEXT NOTEBOOK --***