###  Tensorflow Fundementals:

**Notes:**
* shuffling the tensor is useful when we want to shuffle data so that inherent order doesn't effect learning.

**4) Shuffle the order of elements of tensor using `tf.random.shuffle()`**
* Randomly shuffles a tensor along its first dimension.
* To ensure reproducible shuffling, we need to use both global and operational level seed.

In [1]:
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim

NameError: name 'tf' is not defined

In [8]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [17]:
# shuffling the not_shuffled tensor
tf.random.set_seed(42) # global level seed
tf.random.shuffle(not_shuffled,seed=42) # operation level seed 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

**Understanding effect of seed:**
<br>
Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed. Its interactions with operation-level seeds is as follows:
<br>


In [21]:
# If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
# Conclusion: Every time, the code is runned output will change

not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [35]:
# If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
# Conclusion: Output doesn't change everytime code is run 

not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
tf.random.set_seed(42) # global level seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [28]:
# If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
# Conclusion: Output will change everytime code is run

not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_shuffled,seed=42) # operational seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [32]:
# If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.
# Conclusion: Output doesn't change everytime code is run
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
tf.random.set_seed(42) # global level seed
tf.random.shuffle(not_shuffled,seed=42) # operation level seed 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

***-- CONTD IN NEXT NOTEBOOK --***