###  Tensorflow Fundementals:

**Introduction to tensors**

In [1]:
import tensorflow as tf

2025-02-18 20:58:36.082356: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


**6) Getting information from tensors**
<br>
<br>
<img src="tensor_info.png" width="700">


In [6]:
# creating rank 4 tensor
random1=tf.random.Generator.from_seed(7)
t1=random1.uniform(shape=(2,3,4,5))
t1

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0.39932835, 0.7840713 , 0.67880154, 0.73395896, 0.5520444 ],
         [0.10948515, 0.6487982 , 0.9890779 , 0.8203654 , 0.70470357],
         [0.9578625 , 0.02297425, 0.93598676, 0.6513264 , 0.31663585],
         [0.00111556, 0.9212191 , 0.3822806 , 0.77246034, 0.91514194]],

        [[0.5751133 , 0.793342  , 0.4289763 , 0.19118965, 0.7452506 ],
         [0.41762006, 0.8173511 , 0.20117116, 0.6457157 , 0.16484237],
         [0.4484123 , 0.6057888 , 0.816115  , 0.4129653 , 0.2632984 ],
         [0.19087589, 0.7631861 , 0.8340243 , 0.49447727, 0.6866319 ]],

        [[0.300259  , 0.26729417, 0.83389175, 0.62988555, 0.15143108],
         [0.47044265, 0.69402504, 0.9605911 , 0.93813527, 0.5299927 ],
         [0.21156156, 0.3940668 , 0.16456759, 0.42329657, 0.6732943 ],
         [0.28540838, 0.41686988, 0.74725735, 0.8982729 , 0.95173836]]],


       [[[0.09668875, 0.94335854, 0.6924689 , 0.98699486, 0.9925091 ],
         [0.204

In [7]:
t1[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0.39932835, 0.7840713 , 0.67880154, 0.73395896, 0.5520444 ],
        [0.10948515, 0.6487982 , 0.9890779 , 0.8203654 , 0.70470357],
        [0.9578625 , 0.02297425, 0.93598676, 0.6513264 , 0.31663585],
        [0.00111556, 0.9212191 , 0.3822806 , 0.77246034, 0.91514194]],

       [[0.5751133 , 0.793342  , 0.4289763 , 0.19118965, 0.7452506 ],
        [0.41762006, 0.8173511 , 0.20117116, 0.6457157 , 0.16484237],
        [0.4484123 , 0.6057888 , 0.816115  , 0.4129653 , 0.2632984 ],
        [0.19087589, 0.7631861 , 0.8340243 , 0.49447727, 0.6866319 ]],

       [[0.300259  , 0.26729417, 0.83389175, 0.62988555, 0.15143108],
        [0.47044265, 0.69402504, 0.9605911 , 0.93813527, 0.5299927 ],
        [0.21156156, 0.3940668 , 0.16456759, 0.42329657, 0.6732943 ],
        [0.28540838, 0.41686988, 0.74725735, 0.8982729 , 0.95173836]]],
      dtype=float32)>

In [10]:
t1.shape,t1.ndim,tf.size(t1)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [17]:
# Get other various attributes
print("Datatype of every element: ", t1.dtype)
print("Number of dimensions (rank): ", t1.ndim)
print("Shape of tensor: ", t1.shape)
print("Elements along 0-axis: ", t1.shape[0])
print("Elements along last-axis: ", t1.shape[-1])
print("Total number of elements in our tensor: ", tf.size(t1))
print("Total number of elements in our tensor: ", tf.size(t1).numpy())


Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along 0-axis:  2
Elements along last-axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


***-- CONTD IN NEXT NOTEBOOK --***