###  Tensorflow Fundementals:

In [1]:
import tensorflow as tf

2025-02-19 09:59:14.046697: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


**7) Indexing and expanding tensors**
* Tensors can be indexed like python lists
* When getting first element from all dimensions except a particular one, all dimensions are squeezed.

In [ ]:
# Creating a random tensor

random1=tf.random.Generator.from_seed(7)
t1=random1.uniform(shape=(2,3,4,5))

In [2]:
# Getting first two elements of each dimension in our tensor
t1[:2,:2:,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0.39932835, 0.7840713 ],
         [0.10948515, 0.6487982 ]],

        [[0.5751133 , 0.793342  ],
         [0.41762006, 0.8173511 ]]],


       [[[0.09668875, 0.94335854],
         [0.20401764, 0.26398885]],

        [[0.3422103 , 0.8459996 ],
         [0.95617914, 0.6482675 ]]]], dtype=float32)>

In [7]:
# Getting the first element from each dimension from each index except the final one
print(t1[:1,:1,:1,:]) # this is what is asked by the question
print(t1[0][0][0]) # this is extracting column from the last dimension

tf.Tensor([[[[0.39932835 0.7840713  0.67880154 0.73395896 0.5520444 ]]]], shape=(1, 1, 1, 5), dtype=float32)
tf.Tensor([0.39932835 0.7840713  0.67880154 0.73395896 0.5520444 ], shape=(5,), dtype=float32)


In [8]:
print(t1[:1,:1,:,:1]) # gets first element from each dimension except the second last one (gets all from second last dimension)

tf.Tensor(
[[[[0.39932835]
   [0.10948515]
   [0.9578625 ]
   [0.00111556]]]], shape=(1, 1, 4, 1), dtype=float32)


In [10]:
print(t1[:1,:,:1,:1]) # gets first element from each dimension except the third last one (gets all from second last dimension)

tf.Tensor(
[[[[0.39932835]]

  [[0.5751133 ]]

  [[0.300259  ]]]], shape=(1, 3, 1, 1), dtype=float32)


In [11]:
print(t1[:,:1,:1,:1]) # gets first element from each dimension except the first one (gets all from second last dimension)

tf.Tensor(
[[[[0.39932835]]]


 [[[0.09668875]]]], shape=(2, 1, 1, 1), dtype=float32)


**8) Reshaping the tensor using `tf.reshape()`**

In [16]:
# reshaping the tensor: create a rank 2 tensor
t2=tf.reshape(t1,(3*5,tf.size(t1)//(3*5)))
t2.shape,t2.ndim

(TensorShape([15, 8]), 2)

In [17]:
# getting last item of each row of rank 2 tensor
t2[:,-1]

<tf.Tensor: shape=(15,), dtype=float32, numpy=
array([0.9890779 , 0.00111556, 0.19118965, 0.6057888 , 0.6866319 ,
       0.9605911 , 0.28540838, 0.98699486, 0.78412795, 0.6435729 ,
       0.55495536, 0.42452395, 0.17085445, 0.33849728, 0.93585527],
      dtype=float32)>

**9) Adding an extra dimension to tensor using `tf.newaxis` or `tf.expand_dims()`**
* We don't shape of this numbers, rather change shape of the numbers in which they fit into
* `[...,tf.newaxis] <--> [:,:,:,.. and so on, tf.newaxis]`, `...` consider every previous axis.
* The new axis can be added depending on where you wish to do so
* `tf.expand_dims(tensor,axis)`, instead of explicitly adding a new axis, here we specify the position where we want to add the new axis

In [23]:
# Add a dimension to rank-2 tensor and convert it to rank 3 tensor
t3=t2[:2,:2]
print(t3)
t4=t3[...,tf.newaxis] # adding new axis to end
t4

tf.Tensor(
[[0.39932835 0.7840713 ]
 [0.8203654  0.70470357]], shape=(2, 2), dtype=float32)


<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.39932835],
        [0.7840713 ]],

       [[0.8203654 ],
        [0.70470357]]], dtype=float32)>

In [24]:
t5=t3[:,tf.newaxis,:] 
t5

<tf.Tensor: shape=(2, 1, 2), dtype=float32, numpy=
array([[[0.39932835, 0.7840713 ]],

       [[0.8203654 , 0.70470357]]], dtype=float32)>

In [25]:
t6=tf.expand_dims(t3,axis=-1) # expand on final axis
t6

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.39932835],
        [0.7840713 ]],

       [[0.8203654 ],
        [0.70470357]]], dtype=float32)>

In [26]:
t7=tf.expand_dims(t3,axis=1) # expand on second axis
t7

<tf.Tensor: shape=(2, 1, 2), dtype=float32, numpy=
array([[[0.39932835, 0.7840713 ]],

       [[0.8203654 , 0.70470357]]], dtype=float32)>

In [28]:
t8=tf.expand_dims(t3,axis=0) # expand on first axis
t8

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0.39932835, 0.7840713 ],
        [0.8203654 , 0.70470357]]], dtype=float32)>

***-- CONTD IN NEXT NOTEBOOK --***