###  Tensorflow Fundementals:

In [1]:
import tensorflow as tf

2025-02-19 10:32:18.765538: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


**10) Manipulating tensors with basic operations (+,-,*,/)** 
* To effectively use the GPU it is better to use builtin tensor flow operations compared to operators directly

In [9]:
t1=tf.constant([[10,7],[3,4]])
t1+10
# Adds 10 to each element and original tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [4]:
t1=t1+10 # tensor will be changed
t1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [7]:
t1*10 # multiplication (element multiplied to each element in tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000,  700],
       [ 300,  400]], dtype=int32)>

In [10]:
t1-10 # subtraction (element subtracted from each element in tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

**Using equivalent tensorflow built-in operations**

In [11]:
tf.multiply(t1,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

***-- CONTD IN NEXT NOTEBOOK --***