###  Tensorflow Fundementals:

In [1]:
import tensorflow as tf

2025-02-19 12:47:12.001044: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


**14) Aggregating tensors**
* Aggregation: Condensing tensors from multiple values down to smaller amount of values.
* `tf.abs()`: Computes absolute value of tensor (converts all negative values in tensor to positive values)
* These operations basically ravels the tensor into a single dimension vector/tensor and then applies the operations:
    * `tf.reduce_min()`
    * `tf.reduce_max()`
    * `tf.reduce_mean()`
    * `tf.reduce_sum()`
    * `tf.math.reduce_variance()` (Needs typecasting to float or complex)
    * `tf.math.reduce_std()`: (Needs typecasting to float or complex)

In [2]:
# Getting absolute values
A=tf.constant([-7,10])
tf.abs(A)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [32]:
tf.random.set_seed(14)
a=tf.random.uniform(shape=(50,2),minval=0,maxval=100,dtype=tf.int32)
a

<tf.Tensor: shape=(50, 2), dtype=int32, numpy=
array([[49, 81],
       [19, 14],
       [77, 16],
       [82, 75],
       [91, 84],
       [96, 70],
       [14, 90],
       [91, 48],
       [71, 84],
       [75, 16],
       [40, 46],
       [95, 80],
       [13, 39],
       [99, 10],
       [55, 74],
       [58, 68],
       [27, 63],
       [56, 88],
       [26, 25],
       [69, 57],
       [ 5, 56],
       [81, 91],
       [21, 24],
       [26, 91],
       [89, 20],
       [25, 10],
       [32, 97],
       [57, 16],
       [10, 70],
       [73, 73],
       [51, 93],
       [36, 54],
       [93, 84],
       [59, 49],
       [43, 27],
       [ 2, 89],
       [91, 16],
       [36, 42],
       [ 6, 64],
       [58, 81],
       [ 1, 52],
       [74, 32],
       [32, 54],
       [93, 99],
       [67, 53],
       [65, 30],
       [ 2, 46],
       [89, 80],
       [26, 67],
       [48, 77]], dtype=int32)>

In [18]:
# finding minimum
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [14]:
# finding maximum
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [19]:
# finding mean
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=int32, numpy=52>

In [20]:
# finding sum of tensor
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=int32, numpy=13145>

In [35]:
# finding variance of tensor
tf.math.reduce_variance(tf.cast(a,tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=821.501953125>

In [39]:
# finding standard deviation of tensor
tf.math.reduce_std(tf.cast(a,tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=28.661854441051087>

***-- CONTD IN NEXT NOTEBOOK --***