###  Tensorflow Fundementals:

In [1]:
import tensorflow as tf

2025-02-19 10:44:34.168557: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


**11) Matrix Multiplication**
* shorthand for matrix multiplication using python operator: `@`
* Rules for matrix multiplications:
  * The inner dimensions must match 
  * The resulting matrix has the shape of the outer dimensions
* Using `tf.constant()` or `tf.variable()` we cannot do `tensor.T` to transpose it, rather we need to use tf.transpose(tensor)
* `tf.transpose()` flips the axes while reshape just shuffles the tensor around into shape we want (as long as total number of elements intially and in the new shape can be kept same)
* Generally when performing matrix multiplication and one of the axis doesn't line up we will transpose (rather than reshapping it) to satisfy matrix multiplication rules.

In [2]:
t1=tf.constant([[1,2,3],[4,5,6]])
t2=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
tf.matmul(t1,t2)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]], dtype=int32)>

In [3]:
t1@t2 

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]], dtype=int32)>

In [5]:
t1*t1 # multiplies element by element (elementwise)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [10]:
t1@(tf.transpose(t1))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [19]:
t1@(tf.reshape(t1,shape=(t1.shape[1],t1.shape[0])))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [20]:
tf.reshape(t1,shape=(t1.shape[1],t1.shape[0]))@t1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [21]:
t1,t2

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>)

**12) Dot Product**
* Matrix Multiplication is also a kind of dot product between row space of the first and column space of the second matrix.
* Can be performed using:
  * `tf.matmul()`
  * `tf.tensordot()`: selection of axes decides the result
  * `@`

In [27]:
tf.tensordot(tf.transpose(t1),t1,axes=0)

<tf.Tensor: shape=(3, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 4,  8, 12],
         [16, 20, 24]]],


       [[[ 2,  4,  6],
         [ 8, 10, 12]],

        [[ 5, 10, 15],
         [20, 25, 30]]],


       [[[ 3,  6,  9],
         [12, 15, 18]],

        [[ 6, 12, 18],
         [24, 30, 36]]]], dtype=int32)>

In [28]:
tf.tensordot(tf.transpose(t1),t1,axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

***-- CONTD IN NEXT NOTEBOOK --***