###  Tensorflow Fundementals:

In [1]:
import tensorflow as tf

2025-02-19 13:54:09.604778: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


**17) One Hot Encoding `tf.one_hot(indices:tensor,depth:"number of classes")`**
* used to convert data into numerical form (binary)

In [6]:
data=tf.random.uniform(shape=(25,),minval=0,maxval=9,dtype=tf.int32) # 9 class data (eg: MNIST number recognition)
num_classes=9
data

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([0, 1, 5, 2, 1, 6, 2, 3, 2, 1, 2, 6, 5, 1, 4, 8, 3, 4, 8, 0, 6, 4,
       0, 5, 6], dtype=int32)>

In [7]:
# one hot encode:
tf.one_hot(data,depth=num_classes)

<tf.Tensor: shape=(25, 9), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
      

In [9]:
# specifying custom values for one hot encoding
tf.one_hot(data,depth=num_classes,on_value="Ya",off_value="Na")

<tf.Tensor: shape=(25, 9), dtype=string, numpy=
array([[b'Ya', b'Na', b'Na', b'Na', b'Na', b'Na', b'Na', b'Na', b'Na'],
       [b'Na', b'Ya', b'Na', b'Na', b'Na', b'Na', b'Na', b'Na', b'Na'],
       [b'Na', b'Na', b'Na', b'Na', b'Na', b'Ya', b'Na', b'Na', b'Na'],
       [b'Na', b'Na', b'Ya', b'Na', b'Na', b'Na', b'Na', b'Na', b'Na'],
       [b'Na', b'Ya', b'Na', b'Na', b'Na', b'Na', b'Na', b'Na', b'Na'],
       [b'Na', b'Na', b'Na', b'Na', b'Na', b'Na', b'Ya', b'Na', b'Na'],
       [b'Na', b'Na', b'Ya', b'Na', b'Na', b'Na', b'Na', b'Na', b'Na'],
       [b'Na', b'Na', b'Na', b'Ya', b'Na', b'Na', b'Na', b'Na', b'Na'],
       [b'Na', b'Na', b'Ya', b'Na', b'Na', b'Na', b'Na', b'Na', b'Na'],
       [b'Na', b'Ya', b'Na', b'Na', b'Na', b'Na', b'Na', b'Na', b'Na'],
       [b'Na', b'Na', b'Ya', b'Na', b'Na', b'Na', b'Na', b'Na', b'Na'],
       [b'Na', b'Na', b'Na', b'Na', b'Na', b'Na', b'Ya', b'Na', b'Na'],
       [b'Na', b'Na', b'Na', b'Na', b'Na', b'Ya', b'Na', b'Na', b'Na'],
       [b'Na', b

***-- CONTD IN NEXT NOTEBOOK --***